### ISSUE TITLE
Not Enough Stars

### ISSUE THREAD

**Issue by jeff-hykin** [r3w0p/bobocep#13]
I only found this by broswing random JOSS publications. And I wanted to say, this has the highest quality-to-stars ratio I've ever seen. Great job on everything from the install steps, to the examples, to the code itself. I might even start using it as a template for my python packages.

Only recommendation is; put a link to the readthedocs in the readme!

(You can close this issue whenever you see it)

**Comment by r3w0p** [comment]
Thank you very much for the compliment! I hope it is of great use to you and, should you run into any problems, please let me know!

As for the ReadTheDocs: if you click on the "docs passing" shield, it will take you to the documentation. It's also available in the About section on the GitHub page. I'll make it a bit more explicit in a future update 😁
