### ISSUE TITLE
Web of Things TD support? 

### ISSUE THREAD

**Issue by Citrullin** [r3w0p/bobocep#5]
The keywords of the project says web-of-things, but I couldn't find any reference to WoT/Web of Things in the documentation or code.
Does it support WoT TDs?

**Comment by r3w0p** [comment]
It will in version 1.1, which I am currently working on. I will remove the keyword for now, apologies for any confusion.

**Comment by Citrullin** [comment]
> It will in version 1.1, which I am currently working on. I will remove the keyword for now, apologies for any confusion.

Thank you for this information. I post it on the wot discord then. So people know what is happening here :)
